### ISSUE TITLE
prerequisites to run on linux

### ISSUE THREAD

**Issue by chymian** [CyberPunkMetalHead/new-listings-trading-bot#3]
you are usingsome  `dotnet` which is MS stuff..

what would be necessary to run that on an linux VPS, lets say ubuntu or debian?

**Comment by CyberPunkMetalHead** [comment]
Ah yes, that's only being used to run database migrations locally before building the docker containers. 

You'll need to install the .NET Framework and ef core, think you can install both via apt.

**Comment by chymian** [comment]
thx for super fast answer.

1. what database migrations?
  you are using postgres in a container. can you elaborate a bit pls.
2. can the migration be done in the container during startup, , so one has not to taint the linux system with dotnet stuff?
3. and what should this `ef core` be?
any package names? 
TIA

**Comment by chymian** [comment]
in parallel I chatted with deepssek. maybe this can be from help.
what do you think, should it work?

Here's the optimized setup with minimal host footprint and secrets moved to `.env`:

---

### **1. `.env` File** (create new)
```ini
# Database
POSTGRES_USER=admin
POSTGRES_PASSWORD=securepassword
POSTGRES_DB=data

# App (add others if needed)
ASPNETCORE_ENVIRONMENT=Production
```

---

### **2. `entrypoint.sh`** (create new)
```bash
#!/bin/sh

# Wait for PostgreSQL
until pg_isready -h $DB_HOST -U $POSTGRES_USER -d $POSTGRES_DB; do
  echo "Waiting for database..."
  sleep 2
done

# Run migrations
dotnet ef database update

# Start application
exec dotnet new-listing-bot-cs.dll
```
Make it executable locally before building:
```bash
chmod +x entrypoint.sh
```

---

### **3. Modified `Dockerfile`**
```dockerfile
# Base stage using the SDK image (needed for EF tools)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["new-listing-bot-cs.csproj", "./"]
COPY . . 

WORKDIR "/src/."
RUN dotnet restore "./new-listing-bot-cs.csproj"
RUN dotnet build "./new-listing-bot-cs.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./new-listing-bot-cs.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Final production stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY entrypoint.sh .

# Install EF Core tools
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["./entrypoint.sh"]

# Development stage remains unchanged
FROM build AS dev
WORKDIR /app
COPY . . 
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://+:5000;https://+:5001"]
```

---

### **4. Modified `docker-compose.yml`**
```yaml
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:80"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=database  # Needed for entrypoint.sh
  database:
    container_name: database
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      retries: 5
      timeout: 10s

volumes:
  postgres_data:
    driver: local
```

---

### **Key Improvements**
1. **Secret Management**  
   All credentials moved to `.env` (add this to `.gitignore`)
   
2. **Self-Contained Migrations**  
   EF tools installed in the final image, migrations run automatically

3. **Database Readiness Checks**  
   Proper healthcheck and connection waiting

4. **Isolated Dependencies**  
   .NET SDK/EF tools only exist inside containers

---

### **Usage**
1. Create `.env` with your values
2. Build and run:
   ```bash
   docker compose up --build
   ```
3. For development:
   ```bash
   docker compose -f docker-compose.yml -f docker-compose.override.yml up --build
   ```

---

### **Security Notes**
- The `.env` file stays on your VPS only
- Database data persists via Docker volume
- No development tools in production image
- Network isolation between app/database
